# Generated by Django 3.2.8 on 2021-11-10 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='autor_id',
            new_name='autor',
        ),
    ]
