# Generated by Django 3.2.8 on 2021-11-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_rename_autor_id_libro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
